[package]
name = "plugin-sdk"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
flate2.workspace = true
plugin-abi.workspace = true
toml.workspace = true
zip.workspace = true

[target.'cfg(windows)'.dependencies]
hooks.workspace = true
lua-api.workspace = true
mlua.workspace = true
tracing.workspace = true
