[package]
name = "plugin-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
plugin-abi.workspace = true
plugin-sdk.workspace = true
serde_json.workspace = true

[target.'cfg(windows)'.dependencies]
hooks.workspace = true
sdk-bridge.workspace = true
sdk-mod-loader.workspace = true
struct-api.workspace = true
tracing.workspace = true
