[workspace]
members = [
    "crates/asm",
    "crates/hooks",
    "crates/host/abi",
    "crates/host/core",
    "crates/mod-loader",
    "crates/sdk/api",
    "crates/rdb",
    "bridges/core",
    "bridges/js",
    "examples/rust/log_plugin",
    "examples/rust/native_mod",
    "tools/moveset-tool",
    "tools/mod-manifest-tool",
    "tools/plugin-manifest-tool",
    "tools/rdb-tool",
    "sdk/plugins/core",
    "sdk/plugins/data",
    "sdk/plugins/data/api",
    "sdk/plugins/runtime",
    "sdk/plugins/debug",
    "sdk/plugins/overlay",
    "sdk/plugins/linkdata",
    "sdk/plugins/rdb",
    "sdk/plugins/rdb/patcher",
    "plugins/moveset_patcher",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
rdb = { path = "crates/rdb" }
struct-api = { path = "sdk/plugins/data/api", package = "oppw4-data" }
asm = { path = "crates/asm" }
hooks = { path = "crates/hooks" }
plugin-abi = { path = "crates/host/abi" }
sdk-bridge = { path = "bridges/core" }
sdk-js-bridge = { path = "bridges/js" }
plugin-host = { path = "crates/host/core" }
sdk-mod-loader = { path = "crates/mod-loader" }
plugin-sdk = { path = "crates/sdk/api" }
rquickjs = { version = "0.11", features = ["loader", "parallel"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
toml = "0.8"
zip = { version = "2", default-features = false, features = ["deflate"] }
flate2 = "1"
