[workspace]
members = [
    "crates/character-bank",
    "crates/asm",
    "crates/hooks",
    "crates/lua-runtime",
    "crates/sdk-abi",
    "crates/sdk-core",
    "crates/sdk-api",
    "crates/rdb",
    "examples/rust/log_plugin",
    "tools/moveset-tool",
    "tools/mod-manifest-tool",
    "tools/plugin-manifest-tool",
    "tools/rdb-tool",
    "official_plugins/skin_patcher",
    "official_plugins/sdk/core",
    "official_plugins/sdk/runtime",
    "official_plugins/sdk/debug",
    "official_plugins/sdk/overlay",
    "official_plugins/sdk/linkdata",
    "official_plugins/sdk/rdb",
    "official_plugins/fx_director",
    "official_plugins/moveset_patcher",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
rdb = { path = "crates/rdb" }
struct-api = { path = "crates/character-bank" }
asm = { path = "crates/asm" }
hooks = { path = "crates/hooks" }
lua-api = { path = "crates/lua-runtime" }
plugin-abi = { path = "crates/sdk-abi" }
plugin-host = { path = "crates/sdk-core" }
plugin-sdk = { path = "crates/sdk-api" }
mlua = { version = "0.10", features = ["lua54", "vendored"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
toml = "0.8"
zip = { version = "2", default-features = false, features = ["deflate"] }
flate2 = "1"
