[package]
name = "oppw4-fx-director-plugin"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]
name = "fx_director"

[dependencies]
asm.workspace = true
struct-api.workspace = true
plugin-sdk.workspace = true
lua-api.workspace = true
toml.workspace = true
zip.workspace = true
mlua.workspace = true
